{
  "name": "award",
  "description": "渐进式web框架",
  "license": "MIT",
  "scripts": {
    "dev": "node scripts/develop",
    "doc": "cd website && npm run start",
    "start": "yarn install && npm run start:boot && npm run start:link",
    "start:boot": "lerna bootstrap && npm run clean && node scripts/notify.js bootstrap",
    "start:link": "node scripts/link",
    "test": "jest",
    "test:coverage": "jest --coverage --silent",
    "test:client": "yarn test:coverage --collectCoverageFrom='packages/{award,award-fetch,award-router,award-utils}/src/**/*.{ts,tsx}'",
    "test:server": "yarn test:coverage --collectCoverageFrom='packages/{award-plugin,award-render,award-server}/src/**/*.{ts,tsx}'",
    "test:tool": "yarn test:coverage --collectCoverageFrom='packages/award-scripts/src/**/*.{ts,tsx}'",
    "clean": "lerna clean --yes",
    "build": "node scripts/build",
    "eslint": "node scripts/eslint",
    "prettier": "node scripts/prettier",
    "pub": "node scripts/publish patch",
    "pub:alpha": "node scripts/publish alpha",
    "pub:beta": "node scripts/publish beta",
    "pub:rc": "node scripts/publish rc"
  },
  "engines": {
    "node": ">=10"
  },
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "2.6.1",
    "@typescript-eslint/eslint-plugin-tslint": "2.6.1",
    "@typescript-eslint/parser": "2.6.1",
    "babel-eslint": "10.0.3",
    "babel-jest": "24.9.0",
    "babel-plugin-jest-hoist": "24.9.0",
    "codecov": "3.6.5",
    "eslint": "6.6.0",
    "tslint": "5.20.1",
    "chokidar": "3.3.0",
    "husky": "3.0.9",
    "enzyme": "3.10.0",
    "enzyme-adapter-react-16": "1.15.2",
    "jest": "24.9.0",
    "jsdom": "15.2.1",
    "koa-body": "4.1.1",
    "lerna": "2.11.0",
    "eslint-config-prettier": "6.5.0",
    "eslint-config-alloy": "3.1.0",
    "eslint-plugin-react": "7.16.0",
    "eslint-plugin-react-hooks": "2.3.0",
    "eslint-plugin-prettier": "3.1.1",
    "eslint-plugin-jest": "23.0.3",
    "eslint-plugin-import": "2.18.2",
    "prettier": "1.19.1",
    "react": "16.13.0",
    "react-dom": "16.13.0",
    "shelljs": "0.8.3",
    "supertest": "4.0.2",
    "ts-jest": "24.1.0",
    "node-notifier": "6.0.0"
  },
  "devDependencies": {
    "@types/react-test-renderer": "16.9.1",
    "@types/react-loadable": "5.5.2",
    "@types/archiver": "3.0.0",
    "@types/babel-types": "7.0.7",
    "@types/bluebird": "3.5.28",
    "@types/chokidar": "2.1.3",
    "@types/core-js": "2.5.2",
    "@types/clean-css": "4.2.1",
    "@types/deasync": "0.1.0",
    "@types/del": "4.0.0",
    "@types/debug": "4.1.5",
    "@types/enzyme": "3.10.3",
    "@types/enzyme-adapter-react-16": "1.0.5",
    "@types/find-up": "4.0.0",
    "@types/fs-extra": "8.0.1",
    "@types/friendly-errors-webpack-plugin": "0.1.2",
    "@types/hoist-non-react-statics": "3.3.1",
    "@types/http-proxy-middleware": "0.19.3",
    "@types/inquirer": "6.5.0",
    "@types/invariant": "2.2.30",
    "@types/jest": "24.0.24",
    "@types/jsdom": "12.2.4",
    "@types/koa-mount": "4.0.0",
    "@types/koa-sslify": "4.0.1",
    "@types/koa-static": "4.0.1",
    "@types/koa-router": "7.0.42",
    "@types/loader-utils": "1.1.3",
    "@types/lodash": "4.14.146",
    "@types/lru-cache": "5.1.0",
    "@types/lodash-webpack-plugin": "0.11.3",
    "@types/md5": "2.1.33",
    "@types/memory-fs": "0.3.2",
    "@types/mockjs": "1.0.2",
    "@types/mini-css-extract-plugin": "0.8.0",
    "@types/node": "12.12.7",
    "@types/node-fetch": "2.5.3",
    "@types/node-sass": "4.11.0",
    "@types/node-zookeeper-client": "0.2.7",
    "@types/isomorphic-fetch": "0.0.35",
    "@types/ora": "3.2.0",
    "@types/progress": "2.0.3",
    "@types/prop-types": "15.7.3",
    "@types/request": "2.48.3",
    "@types/react-is": "16.7.1",
    "@types/react": "16.9.11",
    "@types/react-dom": "16.9.4",
    "@types/react-helmet": "5.0.14",
    "@types/react-redux": "7.1.5",
    "@types/rimraf": "2.0.3",
    "@types/semver": "6.2.0",
    "@types/string-hash": "1.1.1",
    "@types/supertest": "2.0.8",
    "@types/terser-webpack-plugin": "2.2.0",
    "@types/webpack": "^4.41.0",
    "@types/ws": "6.0.3",
    "@types/webpack-dev-middleware": "2.0.3",
    "@types/zen-observable": "0.8.0"
  }
}
