const THRIFT_OPEN = false;
const DOMAIN = '';
const PORT = '';
const THRIFT_MAX_CONNECTIONS = 4;
const API_APIGATEWAY_OPEN = false;
const API_APIGATEWAY_IP = '';
const API_APIGATEWAY_PATH = '';
const TTL = 5000;
const TIMEOUT = 5000;
const IDLE_TIMEOUT = 60000;

export {
  THRIFT_OPEN,
  DOMAIN,
  PORT,
  THRIFT_MAX_CONNECTIONS,
  API_APIGATEWAY_OPEN,
  API_APIGATEWAY_IP,
  API_APIGATEWAY_PATH,
  TTL,
  TIMEOUT,
  IDLE_TIMEOUT
};
